Login
Prakash-Kuikel/assignment pull request #2
Opened 2022-05-31 11:16 UTC by Prakash-Kuikel

Implemented login query using devise and simple_token_authentication gems

2022-06-02 12:09 UTC, lit-poks commented on app/graphql/mutations/delete_post.rb
> +        post.destroy
destroy returns a model, and your graphql return type is a boolean. i think this will throw an error

2022-06-02 12:12 UTC, jigmetnamgyal requested changes

2022-06-02 12:12 UTC, jigmetnamgyal commented on app/graphql/mutations/login.rb
> +      user = User.find_for_database_authentication(email: email)
Use helper class for heavy logic.

2022-06-02 12:12 UTC, jigmetnamgyal commented on app/graphql/types/post_type.rb
>  class Types::PostType < Types::BaseObject
Always use separate file for Types and argument

2022-06-02 12:12 UTC, jigmetnamgyal commented on config/credentials.yml.enc
> +9Q1x90sorZJaAsToSxgS6ArnhN8Pwc5XysJ3olHRVU0lNlCdSapcbKts4wovlyOk3IyLejOTRO/gTwLI5KOb1jaFOpZVlUmqQKhbFdmj01d0MlQqA7ImJT/BxJrN3FARtJeUEja7vmT6iTmAcbJos4GPwfTRS61tpXXWdQFcS5OpWQAV3IhJmwG6+2fPp5jWXytnRc/
Can you please let us know what credential you added. Just the key

2022-06-02 12:14 UTC, imamrb commented on app/controllers/graphql_controller.rb
> +
This can be moved to a private method

2022-06-02 12:15 UTC, Prakash-Kuikel commented on app/graphql/mutations/delete_post.rb
> +        post.destroy
Thank you for the observation. I shall change the return type to a UserType

2022-06-02 12:24 UTC, Prakash-Kuikel commented on app/models/user.rb
> +  has_many :posts
Thank you for the tip!

2022-06-02 12:25 UTC, imamrb commented on db/migrate/20220531100958_create_posts.rb
> +      t.integer :user_id
please make this field as foreign key to user table

2022-06-02 12:32 UTC, Prakash-Kuikel commented on app/graphql/mutations/create_post.rb
> +    null true
null true specifies that it can return a null as well, I think. 
Will keep in mind about the spacing and indentations.

2022-06-02 12:32 UTC, imamrb commented on app/graphql/mutations/delete_user.rb
> +      posts.destroy_all
please use dependent destroy feature https://blog.getcensus.com/cascading-deletes-in-rails/

2022-06-02 12:34 UTC, imamrb commented on app/graphql/mutations/login.rb
> +          return user
We can use guard clause instead of if else for readability https://anthonygharvey.com/guard-clauses-vs-nested-conditionals

2022-06-02 12:35 UTC, lit-poks commented on app/graphql/types/mutation_type.rb
> +
its preferred to not keep spaces here

2022-06-02 12:40 UTC, Prakash-Kuikel commented on app/graphql/mutations/delete_post.rb
> +        post = Post.find(post_id)
Is it by writing mutation inside the mutation_type.rb itself?

2022-06-02 12:42 UTC, Prakash-Kuikel commented on app/graphql/mutations/login.rb
> +      user = User.find_for_database_authentication(email: email)
Thank you for the tip

2022-06-02 12:42 UTC, Prakash-Kuikel commented on app/graphql/types/post_type.rb
>  class Types::PostType < Types::BaseObject
Thank you for the tip. Will keep in mind

2022-06-02 12:43 UTC, Prakash-Kuikel commented on config/credentials.yml.enc
> +9Q1x90sorZJaAsToSxgS6ArnhN8Pwc5XysJ3olHRVU0lNlCdSapcbKts4wovlyOk3IyLejOTRO/gTwLI5KOb1jaFOpZVlUmqQKhbFdmj01d0MlQqA7ImJT/BxJrN3FARtJeUEja7vmT6iTmAcbJos4GPwfTRS61tpXXWdQFcS5OpWQAV3IhJmwG6+2fPp5jWXytnRc/
I don't remember adding any credential. I don't remember using it anywhere

2022-06-06 09:55 UTC, dorjikhandu21 commented on app/controllers/graphql_controller.rb
> +    User.find_by(authentication_token: request.headers['authtoken'])
Do we need this here bro?

2022-06-06 09:55 UTC, dorjikhandu21 commented on app/graphql/mutations/delete_post.rb
> +  def self.visible?(context)
This method seems to be repeating, if you are using this somewhere else, then include this method in base_mutation class, and the inherit your mutation type from base_mutation class.

2022-06-06 09:55 UTC, dorjikhandu21 commented on bin/bundle
> +
Put this bin directory in .gitignore

2022-06-06 10:09 UTC, Prakash-Kuikel commented on app/controllers/graphql_controller.rb
> +    User.find_by(authentication_token: request.headers['authtoken'])
It is essential for finding the current user based on the auth_token sent by client in its HTTP header

2022-06-07 09:26 UTC, dorjikhandu21 commented on app/controllers/graphql_controller.rb
> +    User.find_by(authentication_token: request.headers['authtoken'])
yea, but this should be handle by devise itself, put `before_action: :authenticate_user!` callback in application controller, then check current_user, if is it present put it inside the context. Inside any of you test file do `before {sign_in(user)}` user -> you have created in test

2022-08-17 06:10 UTC, merged